// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MarlikAlmighty/library/models"
)

// AddBookcaseOKCode is the HTTP code returned for type AddBookcaseOK
const AddBookcaseOKCode int = 200

/*AddBookcaseOK OK

swagger:response addBookcaseOK
*/
type AddBookcaseOK struct {
}

// NewAddBookcaseOK creates AddBookcaseOK with default headers values
func NewAddBookcaseOK() *AddBookcaseOK {

	return &AddBookcaseOK{}
}

// WriteResponse to the client
func (o *AddBookcaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddBookcaseBadRequestCode is the HTTP code returned for type AddBookcaseBadRequest
const AddBookcaseBadRequestCode int = 400

/*AddBookcaseBadRequest Bad request

swagger:response addBookcaseBadRequest
*/
type AddBookcaseBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Fail `json:"body,omitempty"`
}

// NewAddBookcaseBadRequest creates AddBookcaseBadRequest with default headers values
func NewAddBookcaseBadRequest() *AddBookcaseBadRequest {

	return &AddBookcaseBadRequest{}
}

// WithPayload adds the payload to the add bookcase bad request response
func (o *AddBookcaseBadRequest) WithPayload(payload *models.Fail) *AddBookcaseBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add bookcase bad request response
func (o *AddBookcaseBadRequest) SetPayload(payload *models.Fail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddBookcaseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
