// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MarlikAlmighty/library/models"
)

// ListAllBookcasesOKCode is the HTTP code returned for type ListAllBookcasesOK
const ListAllBookcasesOKCode int = 200

/*ListAllBookcasesOK OK

swagger:response listAllBookcasesOK
*/
type ListAllBookcasesOK struct {

	/*
	  In: Body
	*/
	Payload models.BookCases `json:"body,omitempty"`
}

// NewListAllBookcasesOK creates ListAllBookcasesOK with default headers values
func NewListAllBookcasesOK() *ListAllBookcasesOK {

	return &ListAllBookcasesOK{}
}

// WithPayload adds the payload to the list all bookcases o k response
func (o *ListAllBookcasesOK) WithPayload(payload models.BookCases) *ListAllBookcasesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all bookcases o k response
func (o *ListAllBookcasesOK) SetPayload(payload models.BookCases) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllBookcasesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.BookCases{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListAllBookcasesBadRequestCode is the HTTP code returned for type ListAllBookcasesBadRequest
const ListAllBookcasesBadRequestCode int = 400

/*ListAllBookcasesBadRequest Bad request

swagger:response listAllBookcasesBadRequest
*/
type ListAllBookcasesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Fail `json:"body,omitempty"`
}

// NewListAllBookcasesBadRequest creates ListAllBookcasesBadRequest with default headers values
func NewListAllBookcasesBadRequest() *ListAllBookcasesBadRequest {

	return &ListAllBookcasesBadRequest{}
}

// WithPayload adds the payload to the list all bookcases bad request response
func (o *ListAllBookcasesBadRequest) WithPayload(payload *models.Fail) *ListAllBookcasesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all bookcases bad request response
func (o *ListAllBookcasesBadRequest) SetPayload(payload *models.Fail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllBookcasesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
