// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MarlikAlmighty/library/models"
)

// PutBookcaseOKCode is the HTTP code returned for type PutBookcaseOK
const PutBookcaseOKCode int = 200

/*PutBookcaseOK OK

swagger:response putBookcaseOK
*/
type PutBookcaseOK struct {
}

// NewPutBookcaseOK creates PutBookcaseOK with default headers values
func NewPutBookcaseOK() *PutBookcaseOK {

	return &PutBookcaseOK{}
}

// WriteResponse to the client
func (o *PutBookcaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutBookcaseBadRequestCode is the HTTP code returned for type PutBookcaseBadRequest
const PutBookcaseBadRequestCode int = 400

/*PutBookcaseBadRequest Bad request

swagger:response putBookcaseBadRequest
*/
type PutBookcaseBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Fail `json:"body,omitempty"`
}

// NewPutBookcaseBadRequest creates PutBookcaseBadRequest with default headers values
func NewPutBookcaseBadRequest() *PutBookcaseBadRequest {

	return &PutBookcaseBadRequest{}
}

// WithPayload adds the payload to the put bookcase bad request response
func (o *PutBookcaseBadRequest) WithPayload(payload *models.Fail) *PutBookcaseBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put bookcase bad request response
func (o *PutBookcaseBadRequest) SetPayload(payload *models.Fail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBookcaseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
