version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: "usecase"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "password"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080