swagger: '2.0'
info:
  title: Library API
  description: Simple Library API Server
  version: 1.0.0
  contact:
    email: cryptocoin62@gmail.com
host: localhost
basePath: /
schemes:
  - http
consumes:
  - "application/json; charset=utf-8"
produces:
  - "application/json; charset=utf-8"
paths:
  /shelves:
    get:
      tags:
        - shelves
      summary: Handler for show list shelves
      operationId: shelves
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/Library"
        '400':
          description:  Bad request
          schema:
            $ref: "#/definitions/Fail"
  /shelves/{id}:
    get:
      tags:
        - shelvesID
      summary: Handler for list books on shelf
      operationId: shelvesID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          minimum: 1
          description: Get books by shelves ID.
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/Shelf"
        '400':
          description:  Bad request
          schema:
            $ref: "#/definitions/Fail"
  /book/id/{id}:
    get:
      tags:
        - bookID
      summary: Handler for seek book on id
      operationId: bookID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          minimum: 1
          description: The ID of book.
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/Book"
        '400':
          description:  Bad request
          schema:
            $ref: "#/definitions/Fail"
  /book/name/{name}:
    get:
      tags:
        - bookName
      summary: Handler for seek book on name
      operationId: bookName
      parameters:
        - in: path
          name: name
          required: true
          type: string
          description: The name of book.
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/Book"
        '400':
          description:  Bad request
          schema:
            $ref: "#/definitions/Fail"
  /page/{id}:
    get:
      tags:
        - pageID
      summary: Handler for seek page on id
      operationId: pageID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          minimum: 1
          description: The ID of page.
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/Page"
        '400':
          description:  Bad request
          schema:
            $ref: "#/definitions/Fail"
definitions:
  Library:
    type: array
    items:
      $ref: "#/definitions/Shelf"
  Shelf:
    type: object
    properties:
      ID:
        type: integer
        format: int32
      Number:
        type: integer
        format: int32
      NameShelfs:
        type: string
      Books:
        type: array
        items:
          $ref: "#/definitions/Book"
  Book:
    type: object
    properties:
      ID:
        type: integer
        format: int32
      Author:
        type: string
      Publisher:
        type: string
      NumPages:
        type: integer
        format: int32
      ShelvesID:
        type: integer
        format: int32
      Pages:
        type: array
        items:
          $ref: "#/definitions/Page"
  Page:
    type: object
    properties:
      ID:
        type: integer
        format: int32
      Number:
        type: integer
        format: int32
      Text:
        type: string
      BooksID:
        type: integer
        format: int32
  Fail:
    type: object
    properties:
      Code:
        type: integer
        format: int32
      Message:
        type: string
