// Code generated by go-docs; DO NOT EDIT.

/*
Package restapi Library API
Simple Library API Server


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    Contact: <cryptocoin62@gmail.com>

    Consumes:
    - application/json; charset=utf-8

    Produces:
    - application/json; charset=utf-8

docs:meta
*/
package restapi
