// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Library API
//
//  Simple Library API Server
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  Contact: <cryptocoin62@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
