// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MarlikAlmighty/library/pkg/models"
)

// GetBookByIDReader is a Reader for the GetBookByID structure.
type GetBookByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBookByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBookByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBookByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBookByIDOK creates a GetBookByIDOK with default headers values
func NewGetBookByIDOK() *GetBookByIDOK {
	return &GetBookByIDOK{}
}

/* GetBookByIDOK describes a response with status code 200, with default header values.

OK
*/
type GetBookByIDOK struct {
	Payload *models.Book
}

func (o *GetBookByIDOK) Error() string {
	return fmt.Sprintf("[GET /book/{id}][%d] getBookByIdOK  %+v", 200, o.Payload)
}
func (o *GetBookByIDOK) GetPayload() *models.Book {
	return o.Payload
}

func (o *GetBookByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Book)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBookByIDBadRequest creates a GetBookByIDBadRequest with default headers values
func NewGetBookByIDBadRequest() *GetBookByIDBadRequest {
	return &GetBookByIDBadRequest{}
}

/* GetBookByIDBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetBookByIDBadRequest struct {
	Payload *models.Fail
}

func (o *GetBookByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /book/{id}][%d] getBookByIdBadRequest  %+v", 400, o.Payload)
}
func (o *GetBookByIDBadRequest) GetPayload() *models.Fail {
	return o.Payload
}

func (o *GetBookByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
