// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MarlikAlmighty/library/pkg/models"
)

// NewPutBookParams creates a new PutBookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutBookParams() *PutBookParams {
	return &PutBookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutBookParamsWithTimeout creates a new PutBookParams object
// with the ability to set a timeout on a request.
func NewPutBookParamsWithTimeout(timeout time.Duration) *PutBookParams {
	return &PutBookParams{
		timeout: timeout,
	}
}

// NewPutBookParamsWithContext creates a new PutBookParams object
// with the ability to set a context for a request.
func NewPutBookParamsWithContext(ctx context.Context) *PutBookParams {
	return &PutBookParams{
		Context: ctx,
	}
}

// NewPutBookParamsWithHTTPClient creates a new PutBookParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutBookParamsWithHTTPClient(client *http.Client) *PutBookParams {
	return &PutBookParams{
		HTTPClient: client,
	}
}

/* PutBookParams contains all the parameters to send to the API endpoint
   for the put book operation.

   Typically these are written to a http.Request.
*/
type PutBookParams struct {

	// Update.
	Update *models.Book

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put book params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBookParams) WithDefaults() *PutBookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put book params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put book params
func (o *PutBookParams) WithTimeout(timeout time.Duration) *PutBookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put book params
func (o *PutBookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put book params
func (o *PutBookParams) WithContext(ctx context.Context) *PutBookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put book params
func (o *PutBookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put book params
func (o *PutBookParams) WithHTTPClient(client *http.Client) *PutBookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put book params
func (o *PutBookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdate adds the update to the put book params
func (o *PutBookParams) WithUpdate(update *models.Book) *PutBookParams {
	o.SetUpdate(update)
	return o
}

// SetUpdate adds the update to the put book params
func (o *PutBookParams) SetUpdate(update *models.Book) {
	o.Update = update
}

// WriteToRequest writes these params to a swagger request
func (o *PutBookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Update != nil {
		if err := r.SetBodyParam(o.Update); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
