// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MarlikAlmighty/library/pkg/models"
)

// NewAddBookcaseParams creates a new AddBookcaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddBookcaseParams() *AddBookcaseParams {
	return &AddBookcaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddBookcaseParamsWithTimeout creates a new AddBookcaseParams object
// with the ability to set a timeout on a request.
func NewAddBookcaseParamsWithTimeout(timeout time.Duration) *AddBookcaseParams {
	return &AddBookcaseParams{
		timeout: timeout,
	}
}

// NewAddBookcaseParamsWithContext creates a new AddBookcaseParams object
// with the ability to set a context for a request.
func NewAddBookcaseParamsWithContext(ctx context.Context) *AddBookcaseParams {
	return &AddBookcaseParams{
		Context: ctx,
	}
}

// NewAddBookcaseParamsWithHTTPClient creates a new AddBookcaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddBookcaseParamsWithHTTPClient(client *http.Client) *AddBookcaseParams {
	return &AddBookcaseParams{
		HTTPClient: client,
	}
}

/* AddBookcaseParams contains all the parameters to send to the API endpoint
   for the add bookcase operation.

   Typically these are written to a http.Request.
*/
type AddBookcaseParams struct {

	// Add.
	Add *models.BookCase

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add bookcase params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddBookcaseParams) WithDefaults() *AddBookcaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add bookcase params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddBookcaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add bookcase params
func (o *AddBookcaseParams) WithTimeout(timeout time.Duration) *AddBookcaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add bookcase params
func (o *AddBookcaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add bookcase params
func (o *AddBookcaseParams) WithContext(ctx context.Context) *AddBookcaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add bookcase params
func (o *AddBookcaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add bookcase params
func (o *AddBookcaseParams) WithHTTPClient(client *http.Client) *AddBookcaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add bookcase params
func (o *AddBookcaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAdd adds the add to the add bookcase params
func (o *AddBookcaseParams) WithAdd(add *models.BookCase) *AddBookcaseParams {
	o.SetAdd(add)
	return o
}

// SetAdd adds the add to the add bookcase params
func (o *AddBookcaseParams) SetAdd(add *models.BookCase) {
	o.Add = add
}

// WriteToRequest writes these params to a swagger request
func (o *AddBookcaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Add != nil {
		if err := r.SetBodyParam(o.Add); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
