// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MarlikAlmighty/library/pkg/models"
)

// DeleteBookcaseReader is a Reader for the DeleteBookcase structure.
type DeleteBookcaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBookcaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteBookcaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteBookcaseBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteBookcaseOK creates a DeleteBookcaseOK with default headers values
func NewDeleteBookcaseOK() *DeleteBookcaseOK {
	return &DeleteBookcaseOK{}
}

/* DeleteBookcaseOK describes a response with status code 200, with default header values.

OK
*/
type DeleteBookcaseOK struct {
}

func (o *DeleteBookcaseOK) Error() string {
	return fmt.Sprintf("[DELETE /bookcases/{id}][%d] deleteBookcaseOK ", 200)
}

func (o *DeleteBookcaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBookcaseBadRequest creates a DeleteBookcaseBadRequest with default headers values
func NewDeleteBookcaseBadRequest() *DeleteBookcaseBadRequest {
	return &DeleteBookcaseBadRequest{}
}

/* DeleteBookcaseBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type DeleteBookcaseBadRequest struct {
	Payload *models.Fail
}

func (o *DeleteBookcaseBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /bookcases/{id}][%d] deleteBookcaseBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteBookcaseBadRequest) GetPayload() *models.Fail {
	return o.Payload
}

func (o *DeleteBookcaseBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
