// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteBookcaseParams creates a new DeleteBookcaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteBookcaseParams() *DeleteBookcaseParams {
	return &DeleteBookcaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBookcaseParamsWithTimeout creates a new DeleteBookcaseParams object
// with the ability to set a timeout on a request.
func NewDeleteBookcaseParamsWithTimeout(timeout time.Duration) *DeleteBookcaseParams {
	return &DeleteBookcaseParams{
		timeout: timeout,
	}
}

// NewDeleteBookcaseParamsWithContext creates a new DeleteBookcaseParams object
// with the ability to set a context for a request.
func NewDeleteBookcaseParamsWithContext(ctx context.Context) *DeleteBookcaseParams {
	return &DeleteBookcaseParams{
		Context: ctx,
	}
}

// NewDeleteBookcaseParamsWithHTTPClient creates a new DeleteBookcaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteBookcaseParamsWithHTTPClient(client *http.Client) *DeleteBookcaseParams {
	return &DeleteBookcaseParams{
		HTTPClient: client,
	}
}

/* DeleteBookcaseParams contains all the parameters to send to the API endpoint
   for the delete bookcase operation.

   Typically these are written to a http.Request.
*/
type DeleteBookcaseParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete bookcase params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBookcaseParams) WithDefaults() *DeleteBookcaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete bookcase params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBookcaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete bookcase params
func (o *DeleteBookcaseParams) WithTimeout(timeout time.Duration) *DeleteBookcaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete bookcase params
func (o *DeleteBookcaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete bookcase params
func (o *DeleteBookcaseParams) WithContext(ctx context.Context) *DeleteBookcaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete bookcase params
func (o *DeleteBookcaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete bookcase params
func (o *DeleteBookcaseParams) WithHTTPClient(client *http.Client) *DeleteBookcaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete bookcase params
func (o *DeleteBookcaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete bookcase params
func (o *DeleteBookcaseParams) WithID(id int64) *DeleteBookcaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete bookcase params
func (o *DeleteBookcaseParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBookcaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
