// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MarlikAlmighty/library/pkg/models"
)

// ListAllBookcasesReader is a Reader for the ListAllBookcases structure.
type ListAllBookcasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAllBookcasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAllBookcasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListAllBookcasesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAllBookcasesOK creates a ListAllBookcasesOK with default headers values
func NewListAllBookcasesOK() *ListAllBookcasesOK {
	return &ListAllBookcasesOK{}
}

/* ListAllBookcasesOK describes a response with status code 200, with default header values.

OK
*/
type ListAllBookcasesOK struct {
	Payload models.BookCases
}

func (o *ListAllBookcasesOK) Error() string {
	return fmt.Sprintf("[GET /bookcases][%d] listAllBookcasesOK  %+v", 200, o.Payload)
}
func (o *ListAllBookcasesOK) GetPayload() models.BookCases {
	return o.Payload
}

func (o *ListAllBookcasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAllBookcasesBadRequest creates a ListAllBookcasesBadRequest with default headers values
func NewListAllBookcasesBadRequest() *ListAllBookcasesBadRequest {
	return &ListAllBookcasesBadRequest{}
}

/* ListAllBookcasesBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ListAllBookcasesBadRequest struct {
	Payload *models.Fail
}

func (o *ListAllBookcasesBadRequest) Error() string {
	return fmt.Sprintf("[GET /bookcases][%d] listAllBookcasesBadRequest  %+v", 400, o.Payload)
}
func (o *ListAllBookcasesBadRequest) GetPayload() *models.Fail {
	return o.Payload
}

func (o *ListAllBookcasesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
