// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListAllBooksFromBookcasesParams creates a new ListAllBooksFromBookcasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListAllBooksFromBookcasesParams() *ListAllBooksFromBookcasesParams {
	return &ListAllBooksFromBookcasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListAllBooksFromBookcasesParamsWithTimeout creates a new ListAllBooksFromBookcasesParams object
// with the ability to set a timeout on a request.
func NewListAllBooksFromBookcasesParamsWithTimeout(timeout time.Duration) *ListAllBooksFromBookcasesParams {
	return &ListAllBooksFromBookcasesParams{
		timeout: timeout,
	}
}

// NewListAllBooksFromBookcasesParamsWithContext creates a new ListAllBooksFromBookcasesParams object
// with the ability to set a context for a request.
func NewListAllBooksFromBookcasesParamsWithContext(ctx context.Context) *ListAllBooksFromBookcasesParams {
	return &ListAllBooksFromBookcasesParams{
		Context: ctx,
	}
}

// NewListAllBooksFromBookcasesParamsWithHTTPClient creates a new ListAllBooksFromBookcasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListAllBooksFromBookcasesParamsWithHTTPClient(client *http.Client) *ListAllBooksFromBookcasesParams {
	return &ListAllBooksFromBookcasesParams{
		HTTPClient: client,
	}
}

/* ListAllBooksFromBookcasesParams contains all the parameters to send to the API endpoint
   for the list all books from bookcases operation.

   Typically these are written to a http.Request.
*/
type ListAllBooksFromBookcasesParams struct {

	// ID.
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list all books from bookcases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListAllBooksFromBookcasesParams) WithDefaults() *ListAllBooksFromBookcasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list all books from bookcases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListAllBooksFromBookcasesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list all books from bookcases params
func (o *ListAllBooksFromBookcasesParams) WithTimeout(timeout time.Duration) *ListAllBooksFromBookcasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all books from bookcases params
func (o *ListAllBooksFromBookcasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all books from bookcases params
func (o *ListAllBooksFromBookcasesParams) WithContext(ctx context.Context) *ListAllBooksFromBookcasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all books from bookcases params
func (o *ListAllBooksFromBookcasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all books from bookcases params
func (o *ListAllBooksFromBookcasesParams) WithHTTPClient(client *http.Client) *ListAllBooksFromBookcasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all books from bookcases params
func (o *ListAllBooksFromBookcasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list all books from bookcases params
func (o *ListAllBooksFromBookcasesParams) WithID(id int64) *ListAllBooksFromBookcasesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list all books from bookcases params
func (o *ListAllBooksFromBookcasesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllBooksFromBookcasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
