// Code generated by go-swagger; DO NOT EDIT.

package bookcases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MarlikAlmighty/library/pkg/models"
)

// NewPutBookcaseParams creates a new PutBookcaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutBookcaseParams() *PutBookcaseParams {
	return &PutBookcaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutBookcaseParamsWithTimeout creates a new PutBookcaseParams object
// with the ability to set a timeout on a request.
func NewPutBookcaseParamsWithTimeout(timeout time.Duration) *PutBookcaseParams {
	return &PutBookcaseParams{
		timeout: timeout,
	}
}

// NewPutBookcaseParamsWithContext creates a new PutBookcaseParams object
// with the ability to set a context for a request.
func NewPutBookcaseParamsWithContext(ctx context.Context) *PutBookcaseParams {
	return &PutBookcaseParams{
		Context: ctx,
	}
}

// NewPutBookcaseParamsWithHTTPClient creates a new PutBookcaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutBookcaseParamsWithHTTPClient(client *http.Client) *PutBookcaseParams {
	return &PutBookcaseParams{
		HTTPClient: client,
	}
}

/* PutBookcaseParams contains all the parameters to send to the API endpoint
   for the put bookcase operation.

   Typically these are written to a http.Request.
*/
type PutBookcaseParams struct {

	// Update.
	Update *models.BookCase

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put bookcase params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBookcaseParams) WithDefaults() *PutBookcaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put bookcase params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBookcaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put bookcase params
func (o *PutBookcaseParams) WithTimeout(timeout time.Duration) *PutBookcaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put bookcase params
func (o *PutBookcaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put bookcase params
func (o *PutBookcaseParams) WithContext(ctx context.Context) *PutBookcaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put bookcase params
func (o *PutBookcaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put bookcase params
func (o *PutBookcaseParams) WithHTTPClient(client *http.Client) *PutBookcaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put bookcase params
func (o *PutBookcaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdate adds the update to the put bookcase params
func (o *PutBookcaseParams) WithUpdate(update *models.BookCase) *PutBookcaseParams {
	o.SetUpdate(update)
	return o
}

// SetUpdate adds the update to the put bookcase params
func (o *PutBookcaseParams) SetUpdate(update *models.BookCase) {
	o.Update = update
}

// WriteToRequest writes these params to a swagger request
func (o *PutBookcaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Update != nil {
		if err := r.SetBodyParam(o.Update); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
