// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBookByIDHandlerFunc turns a function with the right signature into a get book by id handler
type GetBookByIDHandlerFunc func(GetBookByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBookByIDHandlerFunc) Handle(params GetBookByIDParams) middleware.Responder {
	return fn(params)
}

// GetBookByIDHandler interface for that can handle valid get book by id params
type GetBookByIDHandler interface {
	Handle(GetBookByIDParams) middleware.Responder
}

// NewGetBookByID creates a new http.Handler for the get book by id operation
func NewGetBookByID(ctx *middleware.Context, handler GetBookByIDHandler) *GetBookByID {
	return &GetBookByID{Context: ctx, Handler: handler}
}

/* GetBookByID swagger:route GET /book/{id} books getBookById

Get book by id

*/
type GetBookByID struct {
	Context *middleware.Context
	Handler GetBookByIDHandler
}

func (o *GetBookByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBookByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
