// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAllBooksHandlerFunc turns a function with the right signature into a list all books handler
type ListAllBooksHandlerFunc func(ListAllBooksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllBooksHandlerFunc) Handle(params ListAllBooksParams) middleware.Responder {
	return fn(params)
}

// ListAllBooksHandler interface for that can handle valid list all books params
type ListAllBooksHandler interface {
	Handle(ListAllBooksParams) middleware.Responder
}

// NewListAllBooks creates a new http.Handler for the list all books operation
func NewListAllBooks(ctx *middleware.Context, handler ListAllBooksHandler) *ListAllBooks {
	return &ListAllBooks{Context: ctx, Handler: handler}
}

/* ListAllBooks swagger:route GET /books books listAllBooks

Show all books

*/
type ListAllBooks struct {
	Context *middleware.Context
	Handler ListAllBooksHandler
}

func (o *ListAllBooks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListAllBooksParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
