// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MarlikAlmighty/library/models"
)

// PutBookOKCode is the HTTP code returned for type PutBookOK
const PutBookOKCode int = 200

/*PutBookOK OK

swagger:response putBookOK
*/
type PutBookOK struct {
}

// NewPutBookOK creates PutBookOK with default headers values
func NewPutBookOK() *PutBookOK {

	return &PutBookOK{}
}

// WriteResponse to the client
func (o *PutBookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutBookBadRequestCode is the HTTP code returned for type PutBookBadRequest
const PutBookBadRequestCode int = 400

/*PutBookBadRequest Bad request

swagger:response putBookBadRequest
*/
type PutBookBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Fail `json:"body,omitempty"`
}

// NewPutBookBadRequest creates PutBookBadRequest with default headers values
func NewPutBookBadRequest() *PutBookBadRequest {

	return &PutBookBadRequest{}
}

// WithPayload adds the payload to the put book bad request response
func (o *PutBookBadRequest) WithPayload(payload *models.Fail) *PutBookBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put book bad request response
func (o *PutBookBadRequest) SetPayload(payload *models.Fail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBookBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
