name: SI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install golint
      run: go get golang.org/x/lint/golint

    - name: Install golangci-lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1

    - name: go vet
      continue-on-error: true
      run: go vet ./...

    - name: golangci-lint
      continue-on-error: true
      run: golangci-lint run ./...

    - name: golint
      continue-on-error: true
      run: golint -set_exit_status $(go list ./...)

    - name: Test
      run: go test ./...