// Code generated by go-docs; DO NOT EDIT.

package models

// This file was generated by the docs tool.
// Editing this file might prove futile when you re-run the docs generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Fail fail
// docs:model Fail
type Fail struct {

	// code
	Code int32 `json:"Code,omitempty"`

	// message
	Message string `json:"Message,omitempty"`
}

// Validate validates this fail
func (m *Fail) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Fail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Fail) UnmarshalBinary(b []byte) error {
	var res Fail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
